#!/bin/bash
# This script builds your application using maven. It is optional, and disabled by default (the file has no executable permission). 
# To enable, use the command: git update-index --add --chmod +x .openshift/action_hooks/build
tomcat_version=8.5.15
export JAVA_HOME=${OPENSHIFT_DATA_DIR}jdk1.8.0_121
export TOMCAT_HOME=${OPENSHIFT_DATA_DIR}apache-tomcat-${tomcat_version}
export M2_HOME=${OPENSHIFT_DATA_DIR}apache-maven-3.5.0
export PATH=$JAVA_HOME/bin:$M2_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR
mvn --global-settings ${OPENSHIFT_DATA_DIR}maven.xml --version
mvn --global-settings ${OPENSHIFT_DATA_DIR}maven.xml --file pom.xml clean package -DskipTests

