#!/bin/bash
# If your build produces a war file, use this action hook to clean up the build after deploying.
# This action hook is optional, and is not enabled by default (it has no executable permission). 
# To enable, use the command: git update-index --add --chmod +x .openshift/action_hooks/post_deploy
export JAVA_HOME=${OPENSHIFT_DATA_DIR}jdk1.8.0_121
export TOMCAT_HOME=${OPENSHIFT_DATA_DIR}apache-tomcat-8.5.15
export M2_HOME=${OPENSHIFT_DATA_DIR}apache-maven-3.5.0
export PATH=$JAVA_HOME/bin:$M2_HOME/bin:$PATH

# clean up the build folder (to save disk space)
cd $OPENSHIFT_REPO_DIR
mvn --global-settings ${OPENSHIFT_DATA_DIR}maven.xml --file pom.xml clean
