#!/bin/bash
tomcat_version=8.5.15
export JAVA_HOME=${OPENSHIFT_DATA_DIR}jdk1.8.0_121
export TOMCAT_HOME=${OPENSHIFT_DATA_DIR}apache-tomcat-${tomcat_version}
export M2_HOME=${OPENSHIFT_DATA_DIR}apache-maven-3.5.0
export PATH=$JAVA_HOME/bin:$M2_HOME/bin:$PATH

# install java
if [ ! -d $JAVA_HOME ]
then
	java_inst_file=jdk-8u121-linux-x64.tar.gz
	cd $OPENSHIFT_DATA_DIR
	wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/$java_inst_file
	tar -vxf $java_inst_file
	rm -f $java_inst_file
fi

# install tomcat
if [ ! -d $TOMCAT_HOME ]
then
	cd $OPENSHIFT_DATA_DIR
	wget http://www-eu.apache.org/dist/tomcat/tomcat-8/v${tomcat_version}/bin/apache-tomcat-${tomcat_version}.tar.gz
	tar -vxf apache-tomcat-${tomcat_version}.tar.gz
	rm -f apache-tomcat-${tomcat_version}.tar.gz
	
	# replace ports and ip addresses in configuration
	cd $TOMCAT_HOME/conf
	cp server.xml server.xml.original
	
	# Print a trace of simple commands, for commands, case commands, select commands, and arithmetic for commands and their arguments or associated word lists after they are expanded and before they are executed.
	set -x

	sed -i "s#<Server\s*port=\(\"8005\"\)\(.*\)#<Server address=\"$OPENSHIFT_DIY_IP\" port=\"18005\" \2#g" server.xml
	sed -i "s#<Connector\s*port=\(\"8080\"\)\(.*\)#<Connector address=\"$OPENSHIFT_DIY_IP\" port=\"8080\" \2#g;" server.xml
	sed -i "s#<Connector\s*port=\(\"8009\"\)\(.*\)#<Connector address=\"$OPENSHIFT_DIY_IP\" port=\"18009\" \2#g" server.xml	
	sed -i "s#redirectPort=\"8443\"#redirectPort=\"18443\"#g" server.xml
fi

# replace the setenv.sh in the tomcat bin folder
cp -f  $OPENSHIFT_REPO_DIR/.openshift/setenv.sh $TOMCAT_HOME/bin
